name=7Semi_MAX31856
version=1.0.0
author=7Semi <info@7semi.com>
maintainer=7Semi <info@7semi.com>
sentence=Arduino library for MAX31856 thermocouple amplifier.
paragraph=This library provides an easy interface to the MAX31856 thermocouple-to-digital converter. It supports thermocouple configuration, temperature reading, fault detection, and threshold configuration.
category=Sensors
url=
architectures=*
depends=SPI